def exibe():
    print("----------------------------------------------")

print("MENU DE OPÇÔES")
exibe()
print("blah  blah")
print("blah  blah")
print("blah  blah")
exibe()
print("blah  blah")
print("blah  blah")
print("blah  blah")
exibe()
print("blah  blah")
print("blah  blah")
print("blah  blah")
exibe()
print("Tchau, bb")
exibe()